// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for bachata documents */
interface BachataDocumentData {
    /**
     * title field in *bachata*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: bachata.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slice Zone field in *bachata*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: bachata.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<BachataDocumentDataSlicesSlice>;
}
/**
 * Slice for *bachata → Slice Zone*
 *
 */
type BachataDocumentDataSlicesSlice = AcademiesSlice;
/**
 * bachata document from Prismic
 *
 * - **API ID**: `bachata`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BachataDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BachataDocumentData>, "bachata", Lang>;
/** Content for events documents */
interface EventListDocumentData {
    /**
     * title field in *events*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: eventList.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * reference field in *events*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: eventList.reference
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    reference: prismicT.RelationField<"events">;
    /**
     * Slice Zone field in *events*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: eventList.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<EventListDocumentDataSlicesSlice>;
}
/**
 * Slice for *events → Slice Zone*
 *
 */
type EventListDocumentDataSlicesSlice = EventSlice;
/**
 * events document from Prismic
 *
 * - **API ID**: `eventList`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventListDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<EventListDocumentData>, "eventList", Lang>;
/** Content for event documents */
interface EventsDocumentData {
    /**
     * title field in *event*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: events.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * event page title field in *event*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: events.eventPageTitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    eventPageTitle: prismicT.RichTextField;
    /**
     * Slice Zone field in *event*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: events.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<EventsDocumentDataSlicesSlice>;
}
/**
 * Slice for *event → Slice Zone*
 *
 */
type EventsDocumentDataSlicesSlice = EventSlice;
/**
 * event document from Prismic
 *
 * - **API ID**: `events`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<EventsDocumentData>, "events", Lang>;
/** Content for home documents */
interface HomeDocumentData {
    /**
     * title field in *home*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * reference field in *home*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: home.reference
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    reference: prismicT.RelationField;
    /**
     * teacher field in *home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.teacher
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    teacher: prismicT.ImageField<never>;
    /**
     * teacherTitle field in *home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.teacherTitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    teacherTitle: prismicT.KeyTextField;
    /**
     * Teacher description field in *home*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.teacherDescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    teacherDescription: prismicT.RichTextField;
    /**
     * Description field in *home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Slice Zone field in *home*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomeDocumentDataSlicesSlice>;
    /**
     * meta_title field in *home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.metaTitle
     * - **Tab**: SEO.
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    metaTitle: prismicT.KeyTextField;
    /**
     * meta_description field in *home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.metaDescription
     * - **Tab**: SEO.
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    metaDescription: prismicT.KeyTextField;
}
/**
 * Slice for *home → Slice Zone*
 *
 */
type HomeDocumentDataSlicesSlice = HomeGenreSlice;
/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;
/** Content for kizomba documents */
interface KizombaDocumentData {
    /**
     * title field in *kizomba*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: kizomba.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slice Zone field in *kizomba*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: kizomba.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<KizombaDocumentDataSlicesSlice>;
}
/**
 * Slice for *kizomba → Slice Zone*
 *
 */
type KizombaDocumentDataSlicesSlice = AcademiesSlice;
/**
 * kizomba document from Prismic
 *
 * - **API ID**: `kizomba`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KizombaDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<KizombaDocumentData>, "kizomba", Lang>;
/** Content for salsa documents */
interface SalsaDocumentData {
    /**
     * title field in *salsa*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: salsa.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slice Zone field in *salsa*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: salsa.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<SalsaDocumentDataSlicesSlice>;
}
/**
 * Slice for *salsa → Slice Zone*
 *
 */
type SalsaDocumentDataSlicesSlice = AcademiesSlice;
/**
 * salsa document from Prismic
 *
 * - **API ID**: `salsa`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SalsaDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<SalsaDocumentData>, "salsa", Lang>;
/** Content for tango documents */
interface TangoDocumentData {
    /**
     * title field in *tango*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: tango.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slice Zone field in *tango*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: tango.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<TangoDocumentDataSlicesSlice>;
}
/**
 * Slice for *tango → Slice Zone*
 *
 */
type TangoDocumentDataSlicesSlice = AcademiesSlice;
/**
 * tango document from Prismic
 *
 * - **API ID**: `tango`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TangoDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<TangoDocumentData>, "tango", Lang>;
/** Content for teachers documents */
interface TeachersDocumentData {
    /**
     * Main_section field in *teachers*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: teachers.mainSection
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    mainSection: prismicT.RichTextField;
    /**
     * secondary_title field in *teachers*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: teachers.secondary_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    secondary_title: prismicT.TitleField;
    /**
     * Slice Zone field in *teachers*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: teachers.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<TeachersDocumentDataSlicesSlice>;
}
/**
 * Slice for *teachers → Slice Zone*
 *
 */
type TeachersDocumentDataSlicesSlice = TeacherSliceSlice;
/**
 * teachers document from Prismic
 *
 * - **API ID**: `teachers`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeachersDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<TeachersDocumentData>, "teachers", Lang>;
/** Content for zouk documents */
interface ZoukDocumentData {
    /**
     * title field in *zouk*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: zouk.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slice Zone field in *zouk*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: zouk.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ZoukDocumentDataSlicesSlice>;
}
/**
 * Slice for *zouk → Slice Zone*
 *
 */
type ZoukDocumentDataSlicesSlice = AcademiesSlice;
/**
 * zouk document from Prismic
 *
 * - **API ID**: `zouk`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ZoukDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ZoukDocumentData>, "zouk", Lang>;
export type AllDocumentTypes = BachataDocument | EventListDocument | EventsDocument | HomeDocument | KizombaDocument | SalsaDocument | TangoDocument | TeachersDocument | ZoukDocument;
/**
 * Primary content in Academies → Primary
 *
 */
interface AcademiesSliceDefaultPrimary {
    /**
     * Title field in *Academies → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: academies.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Academies → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: academies.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * keyPhrases field in *Academies → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: academies.primary.keyPhrases
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    keyPhrases: prismicT.KeyTextField;
    /**
     * site_description field in *Academies → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: academies.primary.site_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    site_description: prismicT.KeyTextField;
}
/**
 * Item in Academies → Items
 *
 */
export interface AcademiesSliceDefaultItem {
    /**
     * content field in *Academies → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: academies.items[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * image field in *Academies → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: academies.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * start date field in *Academies → Items*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: academies.items[].startDate
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    startDate: prismicT.DateField;
    /**
     * InstagramLinkTo field in *Academies → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: academies.items[].instagramLinkTo
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    instagramLinkTo: prismicT.LinkField;
    /**
     * whatsappNumber field in *Academies → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: academies.items[].whatsappnumber
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    whatsappnumber: prismicT.KeyTextField;
}
/**
 * Default variation for Academies Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Academies`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AcademiesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AcademiesSliceDefaultPrimary>, Simplify<AcademiesSliceDefaultItem>>;
/**
 * Slice variation for *Academies*
 *
 */
type AcademiesSliceVariation = AcademiesSliceDefault;
/**
 * Academies Shared Slice
 *
 * - **API ID**: `academies`
 * - **Description**: `Academies`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AcademiesSlice = prismicT.SharedSlice<"academies", AcademiesSliceVariation>;
/**
 * Item in Event → Items
 *
 */
export interface EventSliceDefaultItem {
    /**
     * image field in *Event → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: event.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * title field in *Event → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: event.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * date field in *Event → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event.items[].date
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    date: prismicT.RichTextField;
    /**
     * description field in *Event → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * url location field in *Event → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event.items[].urlLocation
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    urlLocation: prismicT.KeyTextField;
    /**
     * location ID field in *Event → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: event.items[].locationId
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    locationId: prismicT.SelectField<"bachatea" | "balconzouk" | "socialclub" | "almambo" | "laazotea" | "eloasis" | "latindancecenter" | "matizBello" | "cmDance" | "casaritmo" | "matizRobledo" | "nuevaGuardia" | "grandSocial" | "saborymasna" | "majao" | "danceFree" | "bachataAlparque" | "barcelona" | "QuimbaraBara" | "madera" | "zoukAlParque" | "selinamedellin" | "matizBuenosAires" | "casaritmoLaureles" | "aPuroTango" | "bloodDanceLaureles">;
    /**
     * url Event field in *Event → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event.items[].urlEvent
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    urlEvent: prismicT.KeyTextField;
    /**
     * genres field in *Event → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event.items[].genres
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    genres: prismicT.KeyTextField;
}
/**
 * Default variation for Event Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Event`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EventSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<EventSliceDefaultItem>>;
/**
 * Slice variation for *Event*
 *
 */
type EventSliceVariation = EventSliceDefault;
/**
 * Event Shared Slice
 *
 * - **API ID**: `event`
 * - **Description**: `Event`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EventSlice = prismicT.SharedSlice<"event", EventSliceVariation>;
/**
 * Primary content in HomeGenre → Primary
 *
 */
interface HomeGenreSliceDefaultPrimary {
    /**
     * Title field in *HomeGenre → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: home_genre.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in HomeGenre → Items
 *
 */
export interface HomeGenreSliceDefaultItem {
    /**
     * image field in *HomeGenre → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home_genre.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * title field in *HomeGenre → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: home_genre.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * color wheel field in *HomeGenre → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select a color
     * - **API ID Path**: home_genre.items[].colorWheel
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    colorWheel: prismicT.SelectField<"--radial-primary" | "--radial-secondary" | "--radial-ternary" | "--radial-quartary" | " --radial-blue">;
}
/**
 * Default variation for HomeGenre Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HomeGenre`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeGenreSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HomeGenreSliceDefaultPrimary>, Simplify<HomeGenreSliceDefaultItem>>;
/**
 * Slice variation for *HomeGenre*
 *
 */
type HomeGenreSliceVariation = HomeGenreSliceDefault;
/**
 * HomeGenre Shared Slice
 *
 * - **API ID**: `home_genre`
 * - **Description**: `HomeGenre`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeGenreSlice = prismicT.SharedSlice<"home_genre", HomeGenreSliceVariation>;
/**
 * Item in TeacherSlice → Items
 *
 */
export interface TeacherSliceSliceDefaultItem {
    /**
     * teacher field in *TeacherSlice → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: teacher_slice.items[].teacher
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    teacher: prismicT.ImageField<never>;
    /**
     * Name field in *TeacherSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: teacher_slice.items[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * description field in *TeacherSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: teacher_slice.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * dance genre field in *TeacherSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: teacher_slice.items[].danceGenre
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    danceGenre: prismicT.KeyTextField;
    /**
     * Instagram URL field in *TeacherSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: teacher_slice.items[].instagramUrl
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    instagramUrl: prismicT.KeyTextField;
}
/**
 * Default variation for TeacherSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TeacherSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TeacherSliceSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<TeacherSliceSliceDefaultItem>>;
/**
 * Slice variation for *TeacherSlice*
 *
 */
type TeacherSliceSliceVariation = TeacherSliceSliceDefault;
/**
 * TeacherSlice Shared Slice
 *
 * - **API ID**: `teacher_slice`
 * - **Description**: `TeacherSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TeacherSliceSlice = prismicT.SharedSlice<"teacher_slice", TeacherSliceSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { BachataDocumentData, BachataDocumentDataSlicesSlice, BachataDocument, EventListDocumentData, EventListDocumentDataSlicesSlice, EventListDocument, EventsDocumentData, EventsDocumentDataSlicesSlice, EventsDocument, HomeDocumentData, HomeDocumentDataSlicesSlice, HomeDocument, KizombaDocumentData, KizombaDocumentDataSlicesSlice, KizombaDocument, SalsaDocumentData, SalsaDocumentDataSlicesSlice, SalsaDocument, TangoDocumentData, TangoDocumentDataSlicesSlice, TangoDocument, TeachersDocumentData, TeachersDocumentDataSlicesSlice, TeachersDocument, ZoukDocumentData, ZoukDocumentDataSlicesSlice, ZoukDocument, AllDocumentTypes, AcademiesSliceDefaultPrimary, AcademiesSliceDefaultItem, AcademiesSliceDefault, AcademiesSliceVariation, AcademiesSlice, EventSliceDefaultItem, EventSliceDefault, EventSliceVariation, EventSlice, HomeGenreSliceDefaultPrimary, HomeGenreSliceDefaultItem, HomeGenreSliceDefault, HomeGenreSliceVariation, HomeGenreSlice, TeacherSliceSliceDefaultItem, TeacherSliceSliceDefault, TeacherSliceSliceVariation, TeacherSliceSlice };
    }
}
