// Code generated by Slice Machine. DO NOT EDIT.

import Event from './Event';
import HomeEvents from './HomeEvents';
import HomeGenre from './HomeGenre';

export {
	Event,
	HomeEvents,
	HomeGenre,
};

export const components = {
	event: Event,
	home_events: HomeEvents,
	home_genre: HomeGenre,
};
