// Code generated by Slice Machine. DO NOT EDIT.

import Academies from './Academies';
import Event from './Event';
import HomeGenre from './HomeGenre';
import TeacherSlice from './TeacherSlice';

export {
	Academies,
	Event,
	HomeGenre,
	TeacherSlice,
};

export const components = {
	academies: Academies,
	event: Event,
	home_genre: HomeGenre,
	teacher_slice: TeacherSlice,
};
