import Head from 'next/head'
import Events from '@/components/Events'

export default function Home() {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Events />
      </main>
    </>
  )
}
