import Head from 'next/head'
import Events from '@/components/Events'
import { createClient } from '../prismicio'

export default function EventsPage(props: any) {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Events page={props?.page} />
      </main>
    </>
  )
}

export async function getStaticProps({ previewData }: any) {
  const client = createClient({ previewData })

  const page = await client.getSingle('eventList')

  return {
    props: {
      page,
    },
  }
}