import Head from 'next/head'
import Genres from '@/components/Home/Genres'
import Contact from '@/components/UI-shared/Contact'
import Events from '@/components/Home/Events'
import Banner from '@/components/Home/Banner'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Banner />
        <Genres />
        <Events />
        <Contact />
      </main>
    </>
  )
}
