import Head from 'next/head'

import Teachers from '@/components/Teachers';
import { createClient } from '../../prismicio'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

export default function TeachersPage({ page }: any) {
  return (
    <>
      <Head>
        <title>Teachers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Teachers data={page} />
    </>
  )
}

export async function getStaticProps({ previewData, params, locale }: any) {
  const client = createClient({ previewData });
  const currentLocale = 'es-CO';

  // const page = await client.getSingle(params.pid, { lang: currentLocale})

  return {
    props: {
      ...(await serverSideTranslations(currentLocale, [
        'common',
        'footer',
        'teachers',
      ])),
    },
  }
}