import Head from 'next/head'

import Academy from '@/components/Academy';
import { createClient } from '../../prismicio'

export default function AcademyPage({ page }: any) {
  return (
    <>
      <Head>
        <title>Academy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Academy data={page.data} />
    </>
  )
}

// Generates `/posts/1` and `/posts/2`
export async function getStaticPaths() {
  return {
    paths: [{ params: { pid: 'bachata' } }, { params: { pid: 'salsa' } }],
    fallback: false, // can also be true or 'blocking'
  }
}

export async function getStaticProps({ previewData, params }: any) {
  const client = createClient({ previewData });
  const page = await client.getSingle(params.pid)

  return {
    props: {
      page,
    },
  }
}